[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["rm -f .next/cache/.tsbuildinfo", "pnpm build"]

[start]
cmd = "pnpm start"
